import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { MetaMaskInpageProvider } from "@metamask/providers";
import { ethers } from "ethers";
import origamiNFT from "../../config/abi/OrigamiNFT.json";
import { CONTRACT_ADDRESS } from "../../config/constants/origamiSwords";
import { OrigamiNFT__factory } from "../../typechain-types";
import { OrigamiNFT } from "../../typechain-types/contracts/OrigamiNFT";
import useGetTokensByAddress from "./hooks/useGetTokensByAddress";
import useGetRecentlyMintedTokens from "./hooks/useGetRecentlyMintedTokens";

declare global {
  interface Window {
    ethereum?: MetaMaskInpageProvider;
  }
}

const Nft: NextPage = () => {
  const [currentAccount, setCurrentAccount] = useState("");
  const [nftContract, setNftContract] = useState<OrigamiNFT>();
  const [isLoading, setIsLoading] = useState(false);

  const checkIfWalletIsConnected = async () => {
    try {
      const { ethereum } = window;

      if (!ethereum) {
        alert("Please install MetaMask");
        setIsLoading(false);
        return;
      }

      const accounts = (await ethereum.request({
        method: "eth_accounts",
      })) as string[];

      if (accounts.length !== 0) {
        const account = accounts[0];
        console.log("Connected", account);
        setCurrentAccount(account);
      } else {
        console.log("No authorized account found");
      }
    } catch (error) {
      console.log(error);
    }

    setIsLoading(false);
  };

  const connectWalletAction = async () => {
    try {
      const { ethereum } = window;

      if (!ethereum) {
        alert("Please install MetaMask");
        setIsLoading(false);
        return;
      }

      const accounts = (await ethereum.request({
        method: "eth_requestAccounts",
      })) as string[];

      if (accounts.length !== 0) {
        console.log("Connected", accounts[0]);
        setCurrentAccount(accounts[0]);
      } else {
        console.log("No authorized account found");
      }
    } catch (error) {
      console.log(error);
    }
  };

  // Wallet connection effects
  useEffect(() => {
    setIsLoading(true);
    checkIfWalletIsConnected();
    connectWalletAction();
  }, []);

  // Get contract on component mount
  useEffect(() => {
    const { ethereum } = window;

    if (ethereum) {
      const provider = new ethers.providers.Web3Provider(ethereum as any);
      const signer = provider.getSigner();
      const origamiNFTContract = OrigamiNFT__factory.connect(
        CONTRACT_ADDRESS,
        signer
      );

      setNftContract(origamiNFTContract);
    } else {
      console.log("Ethereum object no found");
    }
  }, []);

  const { nftObjects } = useGetTokensByAddress(
    nftContract as OrigamiNFT,
    currentAccount
  );

  const { recentlyMintedTokens } = useGetRecentlyMintedTokens(
    nftContract as OrigamiNFT
  );
  console.log("get recently minted tokens", recentlyMintedTokens);

  // Contract effects
  useEffect(() => {
    const onNFTMint = async (sender: string, tokenId: number) => {
      console.log(
        `CharacterNFTMinted - sender: ${sender} tokenId: ${tokenId}}`
      );

      if (nftContract) {
        console.log(
          `Your NFT is all done -- see it here: https://testnets.opensea.io/assets/${CONTRACT_ADDRESS}/${tokenId}`
        );
      }
    };

    if (nftContract) {
      // Setup NFT Minted Listener
      nftContract.on("NewOrigamiNFTMinted", onNFTMint);
    }

    return () => {
      // When your component unmounts, let's make sure to clean up this listener

      if (nftContract) {
        nftContract.off("NewOrigamiNFTMinted", onNFTMint);
      }
    };
  }, [nftContract]);

  const minNft = async () => {
    try {
      if (nftContract) {
        setIsLoading(true);
        let txn = await nftContract?.mintOrigamiNFT();
        await txn?.wait();
        setIsLoading(false);
        console.log("mint txn", txn);
      }
    } catch (error) {
      console.log("error minting nft");
      console.log(error);
      setIsLoading(false);
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!currentAccount && (
        <button
          className="cta-button connect-wallet-button"
          onClick={connectWalletAction}
        >
          Connect Wallet To Get Started
        </button>
      )}
      {currentAccount && (
        <span>{`${currentAccount.slice(0, 4)}...${currentAccount.slice(
          -4
        )}`}</span>
      )}

      <button onClick={minNft}>Mint NFT</button>

      <ul>
        {recentlyMintedTokens &&
          recentlyMintedTokens.map((nft) => (
            <li key={nft.name}>
              <h3>{nft.name}</h3>
              <Image src={nft.image} alt="nft image" width={300} height={300} />
              <h4>{nft.description}</h4>
              {nft.attributes.map((attr, index) => (
                <h5 key={index}>
                  {attr.trait_type}: {attr.value}
                </h5>
              ))}
            </li>
          ))}
      </ul>
    </div>
  );
};

export default Nft;
